<?php
/**
 * Tech4TIME — the branding & advertisement page.
 *
 * PHP, and not HTML, because its content is edited at admin.tech4time.bd and
 * arrives here as content/branding.json. Rendered on the server, on this
 * request, from a file on this disk: no fetch, no framework, and the page works
 * with JavaScript switched off. See ADR 0003 and ADR 0010.
 *
 * Everything editable goes through h() EXCEPT the disclaimer's paragraphs,
 * which are rich text and are printed bare — sanitised on the way in by
 * contract_sanitise(), and again on receipt, because a signature proves where
 * a document came from and not what is inside it.
 *
 * The header, footer and dock are emitted by lib/body.php from
 * content/chrome.json. The hero circuit is still literal markup, being
 * decoration with nothing editable in it; tools/check_shared_markup.py holds
 * that one byte-identical to tools/templates/. The scroll-reveal markers
 * below are hand-maintained, because tools/apply_reveals.py reports and skips
 * any page that builds part of itself with a loop, which this one now does.
 *
 * UNLIKE THE CERTIFICATIONS PAGE, THIS ONE NEEDS NO SECOND SPRITE. Nothing
 * here picks an icon at run time: every download button carries #arrow-down,
 * one constant, and it stays a literal href="#arrow-down" below where
 * tools/inject_icons.py can see it. See BRANDING_DOWNLOAD_GLYPH.
 */

declare(strict_types=1);

require_once __DIR__ . '/../../lib/head.php';
require_once __DIR__ . '/../../lib/body.php';
require_once __DIR__ . '/../../lib/branding.php';

$data = branding_load();
?>
<!DOCTYPE html>
<html lang="<?= h(seo_lang()) ?>">
<head>
<?php seo_head('/pages/branding-and-advertisement/', $data['meta'], ['pages/branding.css?v=2'], $data['updated']); ?>
<?php seo_jsonld('/pages/branding-and-advertisement/', $data['meta'], $data['updated']); ?>

<!-- The press kit, as the files it actually offers: one ImageObject per mark,
     one encoding per downloadable file under it. Generated from the same rows
     the page draws, so a hidden mark or a hidden file is in neither. -->
<script type="application/ld+json">
<?= json_encode(branding_page_schema($data), HEAD_JSON_FLAGS) ?>
</script>
</head>

<body class="page">
<!-- icon-sprite:start -->
<svg class="icon-sprite" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
  <symbol id="arrow-down" viewBox="0 0 384 512"><path d="M169.4 470.6c12.5 12.5 32.8 12.5 45.3 0l160-160c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L224 370.8 224 64c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 306.7L54.6 265.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l160 160z"/></symbol>
</svg>
<!-- icon-sprite:end -->

<?php body_header('/pages/branding-and-advertisement/'); ?>

<main class="page__main" id="main">

  <!-- ========================== Hero banner ========================== -->
  <section class="page-hero">
    <!--hero-circuit:start-->
    <!-- The circuitry around the page title. GENERATED - do not edit this file
         or the copy of it in any page. It is extracted from the company's own
         banner artwork, references/t4t_circuitry_6000_2031_300.svg, by
         tools/build_hero_circuit.py, and tools/propagate_shared.py carries it
         out to every page from here.

         It was drawn by hand once, from a description of that artwork. It is
         no longer a description: every trace, pad and via below is the real
         drawing, clipped and fitted, and the numbers are arithmetic anybody can
         redo rather than an afternoon nobody can.

         aria-hidden, and inside the band but behind it: this is texture around
         the title, and it says nothing.

         SIX LAYERS, ONE SET OF GEOMETRY
         Everything is declared once, in the first layer's <defs>. SVG ids are
         document-scoped, so the other five reference the same paths and are
         mirrored in CSS. That is not tidiness - a duplicate id is a hard
         failure in audit_pages.py, so four corners cannot each carry a copy.

         THE BAND TILES; IT IS NOT STRETCHED. IT USED TO BE.
         The bands used preserveAspectRatio="none", on the reasoning that a band
         runs a fixed height across a box whose width is the screen's and
         stretching a horizontal run only makes it a longer run. That is true of
         a run and false of the drawing around it: pads turn to ovals, vias to
         ellipses, every vertical trace thins and every horizontal one thickens.
         Measured, the two scales agreed at exactly ONE viewport -- 1920px, the
         width the artwork was composed for -- and disagreed everywhere else.

         So the viewBox is BAND_TILES tiles wide and the fit is xMidYMid slice,
         which scales UNIFORMLY and crops rather than distorting. The height
         decides the scale, the width never does, and the trace pitch is the
         same at 768px as at 4K. The corners have always used xMinYMin meet, for
         the same reason turned the other way: a fan of 45 degree elbows must
         not shear, and it must stay pinned to its own corner.

         THE BAND IS A HALF, MIRRORED -- AND THAT IS WHAT A TILE IS
         The reference's band is one run about six times as wide as it is tall.
         So the run fills the left half of a 1440-unit tile and the right half is
         its reflection: every pad stays circular and every mark keeps its drawn
         size. Each tile mirrors about its own centre, and BAND_TILES is ODD so
         the viewBox's centre line is a mirror axis too -- the banner's middle
         is still where the two halves meet.
         hero-circuit__charge--mirrored puts them back in step, and circuit.js
         places each band trace twice per visible tile for the same reason.

         A CHARGE IS ONE <use>, AND NEVER A GROUP OF THEM
         This layer once carried the charge on a <g> wrapping a <use> of a
         *group* of traces, on the reasoning that forty animated elements must
         beat two hundred. That reasoning was wrong, and measurably so.
         stroke-dashoffset is an inherited property: animating it on a group
         makes the browser push the new value down through every <use> shadow
         tree beneath it, every frame. Lighthouse put the page's Style & Layout
         work at 4,683ms against 686ms before it, and the site was reported as
         struggling.

         So: the charge goes directly on the <use> that draws the trace, and it
         is deliberately not on every trace. The density here is the STATIC
         drawing, which costs one rasterisation; movement is the expensive part
         and is spent sparingly - three traces in each cluster and three in each
         band half, 24 against 176 drawn. With scripting, circuit.js paints all
         176 on one canvas and switches these off; these are the fallback, and
         the fallback is what the budget is spent on.

         The cost is close to linear in that number: about 1.1ms of style
         recalculation per second per charge, on top of a floor that is the
         static drawing. If you raise it, measure - tools/check_style_budget.py,
         and read the table in docs/10-development/frontend/motion.md first.

         THE FOUR CORNERS SHARE THREE DURATIONS, AND THAT IS ALSO MEASURED
         Everywhere else on this site a shared duration is the fault being
         avoided. Here it is deliberate: twelve distinct durations give twelve
         distinct computed styles, and Chrome can then share none of them
         between elements. That measured 55ms of style recalculation per second
         against 35ms for the same twenty-four charges on three shared ones -
         and the four clusters are mirror images of each other, so sharing a
         phase reads as the board lighting symmetrically rather than as four
         copies of one loop. Within a cluster the three still differ.

         The two bands are the other deliberate exception: one speed, opposite
         directions, because they are one current going round. -->
    <div class="hero-circuit" aria-hidden="true">
      <svg class="hero-circuit__layer hero-circuit__layer--band-top" viewBox="0 0 21600 114" preserveAspectRatio="xMidYMid slice" focusable="false">
        <defs>
        <path id="hc-b0" pathLength="100" d="M717.1 2.2 L684.7 24.8 L684.7 104.2"/>
        <path id="hc-b1" pathLength="100" d="M715.1 21.7 L715.1 109.1"/>
        <path id="hc-b2" pathLength="100" d="M704 2.2 L704 54.1"/>
        <path id="hc-b3" pathLength="100" d="M642.4 2.2 L642.4 26.9 L661.8 38.6 L661.8 99.5"/>
        <path id="hc-b4" pathLength="100" d="M625.3 2.2 L625.3 74.9"/>
        <path id="hc-b5" pathLength="100" d="M578.5 2.2 L575.3 4 L575.3 32.9 L594.7 49 L594.7 109.1"/>
        <path id="hc-b6" pathLength="100" d="M546.4 2.2 L546.4 36.1 L564.1 46.6 L564.1 94.6"/>
        <path id="hc-b7" pathLength="100" d="M533.5 23.6 L533.5 76.7 L498.8 106"/>
        <path id="hc-b8" pathLength="100" d="M499.9 2.2 L499.9 32.9 L514.3 43.1 L514.3 69.3"/>
        <path id="hc-b9" pathLength="100" d="M485.9 2.2 L486.9 2.9 L486.9 32.9 L468.1 47.2 L468.1 92.1"/>
        <path id="hc-b10" pathLength="100" d="M425.1 2.2 L425.1 51.5 L448.6 65.4 L448.6 92.1"/>
        <path id="hc-b11" pathLength="100" d="M443.9 2.2 L443.9 11.8 L407.4 26.3 L407.4 63.9 L429.2 79.8 L429.2 109.1"/>
        <path id="hc-b12" pathLength="100" d="M407.4 2.2 L407.4 8.1"/>
        <path id="hc-b13" pathLength="100" d="M369.3 2.2 L380.3 9.2 L380.3 69.3"/>
        <path id="hc-b14" pathLength="100" d="M325.3 2.2 L324.4 2.9 L324.4 54.1 L347.3 71.2 L347.3 109.1"/>
        <path id="hc-b15" pathLength="100" d="M286.1 2.2 L286.1 9.2 L300.2 18.7 L300.2 92.1"/>
        <path id="hc-b16" pathLength="100" d="M265.6 2.2 L231.9 26.9 L231.9 60.5"/>
        <path id="hc-b17" pathLength="100" d="M244.9 2.2 L279.6 36.1 L279.6 68.1 L253.7 79.8 L253.7 104.2"/>
        <path id="hc-b18" pathLength="100" d="M207.1 2.2 L194.8 11.8 L194.8 85.3 L221.9 109.1"/>
        <path id="hc-b19" pathLength="100" d="M183 2.2 L183 49 L167.1 57.6 L167.1 99.5"/>
        <path id="hc-b20" pathLength="100" d="M147.7 2.2 L147.7 11.8 L100 35.5 L100 104.2"/>
        <path id="hc-b21" pathLength="100" d="M123.8 2.2 L123.8 69.3 L150.6 84.7"/>
        <path id="hc-b22" pathLength="100" d="M59.9 2.2 L59.9 23.8 L84.7 37.3 L84.7 65.4 L66.4 79.8 L66.4 104.2"/>
        <path id="hc-b23" pathLength="100" d="M67 43.1 L44.6 61.3 L44.6 109.1"/>
        <path id="hc-b24" pathLength="100" d="M29.9 2.2 L29.9 43.1 L4.6 59.5 L4.6 84.7 L18.7 92.1 L18.7 109.1"/>
        <path id="hc-b25" pathLength="100" d="M12.2 2.2 L12.2 36.1"/>
        <g id="hc-band-half"><use href="#hc-b0"/><use href="#hc-b1"/><use href="#hc-b2"/><use href="#hc-b3"/><use href="#hc-b4"/><use href="#hc-b5"/><use href="#hc-b6"/><use href="#hc-b7"/><use href="#hc-b8"/><use href="#hc-b9"/><use href="#hc-b10"/><use href="#hc-b11"/><use href="#hc-b12"/><use href="#hc-b13"/><use href="#hc-b14"/><use href="#hc-b15"/><use href="#hc-b16"/><use href="#hc-b17"/><use href="#hc-b18"/><use href="#hc-b19"/><use href="#hc-b20"/><use href="#hc-b21"/><use href="#hc-b22"/><use href="#hc-b23"/><use href="#hc-b24"/><use href="#hc-b25"/></g>
        <g id="hc-band-wires"><use href="#hc-band-half"/><use href="#hc-band-half" transform="translate(1440,0) scale(-1,1)"/></g>
        <g id="hc-band-pads-half"><circle cx="715.2" cy="109.1" r="4.8"/><circle cx="715.2" cy="21.7" r="4.8"/><circle cx="704.1" cy="54.1" r="4.8"/><circle cx="661.9" cy="99.5" r="4.8"/><circle cx="594.8" cy="109.1" r="4.8"/><circle cx="564.2" cy="94.6" r="4.8"/><circle cx="468.2" cy="92.1" r="4.8"/><circle cx="448.7" cy="92.1" r="4.8"/><circle cx="429.3" cy="109.1" r="4.8"/><circle cx="347.4" cy="109.1" r="4.8"/><circle cx="300.3" cy="92.1" r="4.8"/><circle cx="222" cy="109.1" r="4.8"/><circle cx="167.2" cy="99.5" r="4.8"/><circle cx="150.7" cy="84.7" r="4.8"/><circle cx="44.7" cy="109.1" r="4.8"/><circle cx="67.1" cy="43.1" r="4.8"/><circle cx="18.8" cy="109.1" r="4.8"/><circle cx="12.3" cy="36.1" r="4.8"/><path d="M667.9 71.8 L675.5 71.8 L675.5 49.2 L667.9 49.2Z"/><path d="M600.3 54.1 L607.9 54.1 L607.9 46.6 L600.3 46.6Z"/><path d="M600.3 44.5 L607.9 44.5 L607.9 40 L600.3 40Z"/><path d="M600.3 33.4 L607.9 33.4 L607.9 30.6 L600.3 30.6Z"/><path d="M600.3 28.5 L607.9 28.5 L607.9 13.5 L600.3 13.5Z"/><path d="M555.6 14.7 L563.2 14.7 L563.2 9.7 L555.6 9.7Z"/><path d="M555.6 5.8 L563.2 5.8 L563.2 2.3 L555.6 2.3Z"/><path d="M486.7 80.8 L494.3 80.8 L494.3 75.2 L486.7 75.2Z"/><path d="M486.7 68.2 L494.3 68.2 L494.3 63 L486.7 63Z"/><path d="M486.7 59.2 L494.3 59.2 L494.3 40.2 L486.7 40.2Z"/><path d="M486.7 73.4 L494.3 73.4 L494.3 70 L486.7 70Z"/><path d="M453.3 40.6 L460.9 40.6 L460.9 36.5 L453.3 36.5Z"/><path d="M453.3 33.4 L460.9 33.4 L460.9 29.2 L453.3 29.2Z"/><path d="M453.3 24.3 L460.9 24.3 L460.9 21.2 L453.3 21.2Z"/><path d="M453.3 19.8 L460.9 19.8 L460.9 13.1 L453.3 13.1Z"/><path d="M453.3 9.3 L460.9 9.3 L460.9 0 L453.3 0Z"/><path d="M390.1 74.4 L397.7 74.4 L397.7 66.5 L390.1 66.5Z"/><path d="M390.1 64.4 L397.7 64.4 L397.7 55.3 L390.1 55.3Z"/><path d="M390.1 50.8 L397.7 50.8 L397.7 44.9 L390.1 44.9Z"/><path d="M390.1 42.8 L397.7 42.8 L397.7 40.3 L390.1 40.3Z"/><path d="M390.1 38.9 L397.7 38.9 L397.7 33.8 L390.1 33.8Z"/><path d="M354.1 59.2 L361.7 59.2 L361.7 56.7 L354.1 56.7Z"/><path d="M354.1 54.6 L361.7 54.6 L361.7 48.3 L354.1 48.3Z"/><path d="M354.1 47 L361.7 47 L361.7 37.9 L354.1 37.9Z"/><path d="M354.1 29.2 L361.7 29.2 L361.7 23.6 L354.1 23.6Z"/><path d="M354.1 21.2 L361.7 21.2 L361.7 18.5 L354.1 18.5Z"/><path d="M305.9 23.6 L313.4 23.6 L313.4 20.1 L305.9 20.1Z"/><path d="M305.9 17 L313.4 17 L313.4 8.6 L305.9 8.6Z"/><path d="M305.9 6.5 L313.4 6.5 L313.4 1.3 L305.9 1.3Z"/><path d="M254.6 65.4 L262.2 65.4 L262.2 63.3 L254.6 63.3Z"/><path d="M254.6 60.9 L262.2 60.9 L262.2 57.8 L254.6 57.8Z"/><path d="M254.6 56.4 L262.2 56.4 L262.2 49.7 L254.6 49.7Z"/><path d="M254.6 43.8 L262.2 43.8 L262.2 39.3 L254.6 39.3Z"/><path d="M254.6 37.9 L262.2 37.9 L262.2 36 L254.6 36Z"/><path d="M87.7 22.8 L95.3 22.8 L95.3 18.7 L87.7 18.7Z"/><path d="M87.7 17 L95.3 17 L95.3 11.4 L87.7 11.4Z"/><path d="M87.7 10 L95.3 10 L95.3 4.8 L87.7 4.8Z"/><path d="M44.6 46.7 L52.2 46.7 L52.2 39.6 L44.6 39.6Z"/><path d="M44.6 37.9 L52.2 37.9 L52.2 29.9 L44.6 29.9Z"/><path d="M44.6 24.7 L52.2 24.7 L52.2 14.9 L44.6 14.9Z"/><path d="M44.6 12.1 L52.2 12.1 L52.2 5.1 L44.6 5.1Z"/><path d="M155.3 48.5 L162.9 48.5 L162.9 45.2 L155.3 45.2Z"/><path d="M155.3 24 L162.9 24 L162.9 19.1 L155.3 19.1Z"/><path d="M155.3 31.3 L162.9 31.3 L162.9 26.4 L155.3 26.4Z"/><path d="M155.3 43.1 L162.9 43.1 L162.9 36.2 L155.3 36.2Z"/><path d="M25.7 86 L33.3 86 L33.3 80.4 L25.7 80.4Z"/><path d="M25.7 70 L33.3 70 L33.3 64.4 L25.7 64.4Z"/><path d="M25.7 75.5 L33.3 75.5 L33.3 71.3 L25.7 71.3Z"/><path d="M25.7 93.9 L33.3 93.9 L33.3 88.1 L25.7 88.1Z"/><path d="M0 20.3 L7.6 20.3 L7.6 14.9 L0 14.9Z"/><path d="M0 13.1 L7.6 13.1 L7.6 10 L0 10Z"/><path d="M0 7.9 L7.6 7.9 L7.6 5.5 L0 5.5Z"/><path d="M209.6 48.5 L217.2 48.5 L217.2 45.2 L209.6 45.2Z"/><path d="M209.6 42.8 L217.2 42.8 L217.2 36.8 L209.6 36.8Z"/><path d="M209.6 30.6 L217.2 30.6 L217.2 26 L209.6 26Z"/><path d="M209.6 23.3 L217.2 23.3 L217.2 19.1 L209.6 19.1Z"/><path d="M667.9 46.2 L675.5 46.2 L675.5 42.9 L667.9 42.9Z"/><path d="M667.9 40.5 L675.5 40.5 L675.5 37.2 L667.9 37.2Z"/><path d="M667.9 28.3 L675.5 28.3 L675.5 25 L667.9 25Z"/></g>
        <g id="hc-band-pads"><use href="#hc-band-pads-half"/><use href="#hc-band-pads-half" transform="translate(1440,0) scale(-1,1)"/></g>
        <g id="hc-band-rings-half"><circle cx="625.4" cy="79.8" r="4.8"/><circle cx="533.5" cy="18.7" r="4.8"/><circle cx="495.3" cy="109.1" r="4.8"/><circle cx="514.3" cy="74.3" r="4.8"/><circle cx="407.5" cy="13" r="4.8"/><circle cx="380.3" cy="74.3" r="4.8"/><circle cx="253.8" cy="109.1" r="4.8"/><circle cx="232" cy="65.4" r="4.8"/><circle cx="100.1" cy="109.1" r="4.8"/><circle cx="66.5" cy="109.1" r="4.8"/><circle cx="684.8" cy="109.1" r="4.8"/></g>
        <g id="hc-band-rings"><use href="#hc-band-rings-half"/><use href="#hc-band-rings-half" transform="translate(1440,0) scale(-1,1)"/></g>
        <path id="hc-c0" pathLength="100" d="M192.9 2.3 L190.4 26.6"/>
        <path id="hc-c1" pathLength="100" d="M136.8 2.3 L135.7 9.8 L162.7 38"/>
        <path id="hc-c2" pathLength="100" d="M74.5 2.3 L111.3 40.7 L134.5 34 L150.5 50.8"/>
        <path id="hc-c3" pathLength="100" d="M98.2 2.3 L99.2 3.4 L85 36.5 L107.6 60.1 L130.9 55.8 L148.5 74.2"/>
        <path id="hc-c4" pathLength="100" d="M27.9 2.3 L39.2 14.1 L57.8 8 L74.1 25.1"/>
        <path id="hc-c5" pathLength="100" d="M5 57 L57.7 43.5 L93.9 81.3"/>
        <path id="hc-c6" pathLength="100" d="M5 17.9 L25 38.8 L18.7 76.3 L49.5 108.5 L74.2 104.2 L97.1 128"/>
        <path id="hc-c7" pathLength="100" d="M5 103.9 L13 102.1 L57.2 148.3"/>
        <path id="hc-c8" pathLength="100" d="M5 126.8 L10.6 126.6 L29.8 146.7 L20.5 171.1 L35.2 186.4"/>
        <path id="hc-c9" pathLength="100" d="M5 211.6 L18.2 210.4"/>
        <path id="hc-c10" pathLength="100" d="M176.4 2.3 L187.2 13.6 L177.9 37.9 L192.6 53.3"/>
        <path id="hc-c11" pathLength="100" d="M103.9 2.3 L104.2 2.7 L100 33.9 L144.2 80.1 L175.6 77.3"/>
        <path id="hc-c12" pathLength="100" d="M46.7 2.3 L46.5 14.3 L64.1 32.7 L78.7 27.1 L115 65 L110.2 80.9 L135.3 107.2"/>
        <path id="hc-c13" pathLength="100" d="M11.7 25.2 L24.3 38.3 L42 35.2 L70.4 64.8 L54.6 111 L96 154.2"/>
        <path id="hc-c14" pathLength="100" d="M5 64.3 L33.3 57.5 L90 116.7 L116.1 108.7"/>
        <path id="hc-c15" pathLength="100" d="M5 111.8 L22.4 130 L46.1 122.3 L63 139.9 L60.2 160.9 L74.9 176.3"/>
        <path id="hc-c16" pathLength="100" d="M38.5 137.5 L35.4 163.6 L64.1 193.7"/>
        <path id="hc-c17" pathLength="100" d="M5 151.2 L15.1 161.8 L9.1 188.8 L24.3 204.7 L37.6 200 L47.8 210.7"/>
        <g id="hc-corner-wires"><use href="#hc-c0"/><use href="#hc-c1"/><use href="#hc-c2"/><use href="#hc-c3"/><use href="#hc-c4"/><use href="#hc-c5"/><use href="#hc-c6"/><use href="#hc-c7"/><use href="#hc-c8"/><use href="#hc-c9"/><use href="#hc-c10"/><use href="#hc-c11"/><use href="#hc-c12"/><use href="#hc-c13"/><use href="#hc-c14"/><use href="#hc-c15"/><use href="#hc-c16"/><use href="#hc-c17"/></g>
        <g id="hc-corner-pads"><circle cx="162.8" cy="38" r="4.3"/><circle cx="150.6" cy="50.7" r="4.3"/><circle cx="148.6" cy="74.2" r="4.3"/><circle cx="97.1" cy="128" r="4.3"/><circle cx="55.1" cy="146.6" r="4.3"/><circle cx="18.2" cy="210.4" r="4.3"/><path d="M172.4 13.7 L169 10.2 L164.3 15.2 L167.7 18.7Z"/><path d="M164.8 5.8 L161.7 2.5 L156.9 7.5 L160.1 10.8Z"/><path d="M168 9.1 L165.9 6.9 L161.1 11.9 L163.2 14.1Z"/><path d="M127.3 10.3 L124.8 7.7 L120 12.7 L122.5 15.3Z"/><path d="M122.9 5.8 L120.4 3.1 L115.6 8.1 L118.1 10.8Z"/><path d="M69.3 3.9 L65.5 0 L60.7 5 L64.5 8.9Z"/><path d="M44.2 32.9 L40.8 29.3 L36 34.3 L39.4 37.9Z"/><path d="M37.6 26.1 L34.3 22.6 L29.5 27.5 L32.9 31.1Z"/><path d="M32.6 20.8 L26.3 14.2 L21.5 19.2 L27.8 25.8Z"/><path d="M23.8 11.6 L19.7 7.4 L15 12.4 L19 16.6Z"/><path d="M107.9 73.1 L103.1 68.1 L98.3 73.1 L103.1 78.1Z"/><path d="M101.8 66.8 L96.4 61.1 L91.6 66.1 L97 71.8Z"/><path d="M93.6 58.3 L90.1 54.5 L85.3 59.5 L88.9 63.2Z"/><path d="M88.8 53.2 L87.3 51.7 L82.5 56.7 L84 58.2Z"/><path d="M86.5 50.8 L83.4 47.6 L78.6 52.6 L81.7 55.8Z"/><path d="M76.1 87.2 L74.6 85.6 L69.8 90.6 L71.3 92.1Z"/><path d="M73.3 84.3 L69.5 80.4 L64.8 85.4 L68.5 89.3Z"/><path d="M68.7 79.5 L63.3 73.8 L58.5 78.8 L63.9 84.5Z"/><path d="M58 68.3 L54.7 64.8 L49.9 69.8 L53.2 73.3Z"/><path d="M53.2 63.3 L51.6 61.6 L46.8 66.6 L48.4 68.3Z"/><path d="M24.3 96.5 L22.2 94.3 L17.4 99.3 L19.5 101.5Z"/><path d="M20.3 92.4 L15.3 87.1 L10.5 92.1 L15.5 97.3Z"/><path d="M14 85.8 L10.9 82.5 L6.1 87.5 L9.3 90.8Z"/><path d="M9.6 81.2 L6.5 77.9 L1.7 82.9 L4.8 86.2Z"/><path d="M12.9 41.3 L10.6 38.9 L5.9 43.9 L8.1 46.3Z"/><path d="M10 38.3 L4.8 32.8 L0 37.8 L5.2 43.2Z"/><path d="M17.3 156.5 L16 155.1 L11.2 160.1 L12.5 161.5Z"/><path d="M14.5 153.6 L12.6 151.6 L7.9 156.6 L9.8 158.6Z"/><path d="M11.8 150.8 L7.8 146.6 L3 151.6 L7 155.8Z"/><circle cx="175.6" cy="77.3" r="4.3"/><circle cx="135.4" cy="107.1" r="4.3"/><circle cx="116.1" cy="108.7" r="4.3"/><circle cx="64.1" cy="193.7" r="4.3"/><circle cx="38.5" cy="141.8" r="4.3"/><circle cx="47.8" cy="210.7" r="4.3"/><path d="M90.6 153.3 L88.1 150.7 L83.4 155.7 L85.8 158.3Z"/><path d="M76.8 138.9 L69.9 131.7 L65.1 136.6 L72 143.9Z"/><path d="M65.7 127.3 L61.5 122.9 L56.7 127.9 L60.9 132.3Z"/><path d="M87.1 149.6 L83.7 146.1 L78.9 151.1 L82.3 154.6Z"/><path d="M82.9 145.2 L79.7 142 L75 146.9 L78.1 150.2Z"/><path d="M136.2 42.3 L134.2 40.2 L129.4 45.2 L131.4 47.3Z"/><path d="M132.7 38.6 L129.1 34.9 L124.4 39.9 L127.9 43.6Z"/><path d="M125.4 31 L122.6 28.1 L117.9 33.1 L120.6 36Z"/><path d="M121 26.4 L118.5 23.8 L113.7 28.7 L116.2 31.4Z"/></g>
        <g id="hc-corner-rings"><circle cx="190.1" cy="30.9" r="4.3"/><circle cx="77.1" cy="28.1" r="4.3"/><circle cx="96.9" cy="84.4" r="4.3"/><circle cx="38.2" cy="189.5" r="4.3"/><circle cx="195.6" cy="56.3" r="4.3"/><circle cx="99" cy="157.3" r="4.3"/><circle cx="77.8" cy="179.4" r="4.3"/></g>
        </defs>
        <g class="hero-circuit__wires"><use href="#hc-band-wires"/><use href="#hc-band-wires" transform="translate(1440,0)"/><use href="#hc-band-wires" transform="translate(2880,0)"/><use href="#hc-band-wires" transform="translate(4320,0)"/><use href="#hc-band-wires" transform="translate(5760,0)"/><use href="#hc-band-wires" transform="translate(7200,0)"/><use href="#hc-band-wires" transform="translate(8640,0)"/><use href="#hc-band-wires" transform="translate(10080,0)"/><use href="#hc-band-wires" transform="translate(11520,0)"/><use href="#hc-band-wires" transform="translate(12960,0)"/><use href="#hc-band-wires" transform="translate(14400,0)"/><use href="#hc-band-wires" transform="translate(15840,0)"/><use href="#hc-band-wires" transform="translate(17280,0)"/><use href="#hc-band-wires" transform="translate(18720,0)"/><use href="#hc-band-wires" transform="translate(20160,0)"/></g>
        <g class="hero-circuit__pads"><use href="#hc-band-pads"/><use href="#hc-band-pads" transform="translate(1440,0)"/><use href="#hc-band-pads" transform="translate(2880,0)"/><use href="#hc-band-pads" transform="translate(4320,0)"/><use href="#hc-band-pads" transform="translate(5760,0)"/><use href="#hc-band-pads" transform="translate(7200,0)"/><use href="#hc-band-pads" transform="translate(8640,0)"/><use href="#hc-band-pads" transform="translate(10080,0)"/><use href="#hc-band-pads" transform="translate(11520,0)"/><use href="#hc-band-pads" transform="translate(12960,0)"/><use href="#hc-band-pads" transform="translate(14400,0)"/><use href="#hc-band-pads" transform="translate(15840,0)"/><use href="#hc-band-pads" transform="translate(17280,0)"/><use href="#hc-band-pads" transform="translate(18720,0)"/><use href="#hc-band-pads" transform="translate(20160,0)"/></g>
        <g class="hero-circuit__rings"><use href="#hc-band-rings"/><use href="#hc-band-rings" transform="translate(1440,0)"/><use href="#hc-band-rings" transform="translate(2880,0)"/><use href="#hc-band-rings" transform="translate(4320,0)"/><use href="#hc-band-rings" transform="translate(5760,0)"/><use href="#hc-band-rings" transform="translate(7200,0)"/><use href="#hc-band-rings" transform="translate(8640,0)"/><use href="#hc-band-rings" transform="translate(10080,0)"/><use href="#hc-band-rings" transform="translate(11520,0)"/><use href="#hc-band-rings" transform="translate(12960,0)"/><use href="#hc-band-rings" transform="translate(14400,0)"/><use href="#hc-band-rings" transform="translate(15840,0)"/><use href="#hc-band-rings" transform="translate(17280,0)"/><use href="#hc-band-rings" transform="translate(18720,0)"/><use href="#hc-band-rings" transform="translate(20160,0)"/></g>
        <g class="hero-circuit__charges" transform="translate(10080,0)">
          <use class="hero-circuit__charge hero-circuit__charge--band hero-circuit__charge--p1" href="#hc-b4"/>
          <use class="hero-circuit__charge hero-circuit__charge--band hero-circuit__charge--p2" href="#hc-b12"/>
          <use class="hero-circuit__charge hero-circuit__charge--band hero-circuit__charge--p3" href="#hc-b21"/>
          <g transform="translate(1440,0) scale(-1,1)">
            <use class="hero-circuit__charge hero-circuit__charge--band hero-circuit__charge--mirrored hero-circuit__charge--p1" href="#hc-b4"/>
            <use class="hero-circuit__charge hero-circuit__charge--band hero-circuit__charge--mirrored hero-circuit__charge--p2" href="#hc-b12"/>
            <use class="hero-circuit__charge hero-circuit__charge--band hero-circuit__charge--mirrored hero-circuit__charge--p3" href="#hc-b21"/>
          </g>
        </g>
        <g class="hero-circuit__nodes" transform="translate(10080,0)">
          <circle class="hero-circuit__node hero-circuit__node--a" cx="594.8" cy="109.1" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--b" cx="150.7" cy="84.7" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--c" cx="845.2" cy="109.1" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--d" cx="1289.3" cy="84.7" r="3.6"/>
        </g>
      </svg>
      <svg class="hero-circuit__layer hero-circuit__layer--band-bottom" viewBox="0 0 21600 114" preserveAspectRatio="xMidYMid slice" focusable="false">
        <g class="hero-circuit__wires"><use href="#hc-band-wires"/><use href="#hc-band-wires" transform="translate(1440,0)"/><use href="#hc-band-wires" transform="translate(2880,0)"/><use href="#hc-band-wires" transform="translate(4320,0)"/><use href="#hc-band-wires" transform="translate(5760,0)"/><use href="#hc-band-wires" transform="translate(7200,0)"/><use href="#hc-band-wires" transform="translate(8640,0)"/><use href="#hc-band-wires" transform="translate(10080,0)"/><use href="#hc-band-wires" transform="translate(11520,0)"/><use href="#hc-band-wires" transform="translate(12960,0)"/><use href="#hc-band-wires" transform="translate(14400,0)"/><use href="#hc-band-wires" transform="translate(15840,0)"/><use href="#hc-band-wires" transform="translate(17280,0)"/><use href="#hc-band-wires" transform="translate(18720,0)"/><use href="#hc-band-wires" transform="translate(20160,0)"/></g>
        <g class="hero-circuit__pads"><use href="#hc-band-pads"/><use href="#hc-band-pads" transform="translate(1440,0)"/><use href="#hc-band-pads" transform="translate(2880,0)"/><use href="#hc-band-pads" transform="translate(4320,0)"/><use href="#hc-band-pads" transform="translate(5760,0)"/><use href="#hc-band-pads" transform="translate(7200,0)"/><use href="#hc-band-pads" transform="translate(8640,0)"/><use href="#hc-band-pads" transform="translate(10080,0)"/><use href="#hc-band-pads" transform="translate(11520,0)"/><use href="#hc-band-pads" transform="translate(12960,0)"/><use href="#hc-band-pads" transform="translate(14400,0)"/><use href="#hc-band-pads" transform="translate(15840,0)"/><use href="#hc-band-pads" transform="translate(17280,0)"/><use href="#hc-band-pads" transform="translate(18720,0)"/><use href="#hc-band-pads" transform="translate(20160,0)"/></g>
        <g class="hero-circuit__rings"><use href="#hc-band-rings"/><use href="#hc-band-rings" transform="translate(1440,0)"/><use href="#hc-band-rings" transform="translate(2880,0)"/><use href="#hc-band-rings" transform="translate(4320,0)"/><use href="#hc-band-rings" transform="translate(5760,0)"/><use href="#hc-band-rings" transform="translate(7200,0)"/><use href="#hc-band-rings" transform="translate(8640,0)"/><use href="#hc-band-rings" transform="translate(10080,0)"/><use href="#hc-band-rings" transform="translate(11520,0)"/><use href="#hc-band-rings" transform="translate(12960,0)"/><use href="#hc-band-rings" transform="translate(14400,0)"/><use href="#hc-band-rings" transform="translate(15840,0)"/><use href="#hc-band-rings" transform="translate(17280,0)"/><use href="#hc-band-rings" transform="translate(18720,0)"/><use href="#hc-band-rings" transform="translate(20160,0)"/></g>
        <g class="hero-circuit__charges" transform="translate(10080,0)">
          <use class="hero-circuit__charge hero-circuit__charge--band hero-circuit__charge--p1" href="#hc-b4"/>
          <use class="hero-circuit__charge hero-circuit__charge--band hero-circuit__charge--p2" href="#hc-b12"/>
          <use class="hero-circuit__charge hero-circuit__charge--band hero-circuit__charge--p3" href="#hc-b21"/>
          <g transform="translate(1440,0) scale(-1,1)">
            <use class="hero-circuit__charge hero-circuit__charge--band hero-circuit__charge--mirrored hero-circuit__charge--p1" href="#hc-b4"/>
            <use class="hero-circuit__charge hero-circuit__charge--band hero-circuit__charge--mirrored hero-circuit__charge--p2" href="#hc-b12"/>
            <use class="hero-circuit__charge hero-circuit__charge--band hero-circuit__charge--mirrored hero-circuit__charge--p3" href="#hc-b21"/>
          </g>
        </g>
        <g class="hero-circuit__nodes" transform="translate(10080,0)">
          <circle class="hero-circuit__node hero-circuit__node--e" cx="594.8" cy="109.1" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--f" cx="150.7" cy="84.7" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--g" cx="845.2" cy="109.1" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--h" cx="1289.3" cy="84.7" r="3.6"/>
        </g>
      </svg>
      <svg class="hero-circuit__layer hero-circuit__layer--corner-tl" viewBox="0 0 200 215" preserveAspectRatio="xMinYMin meet" focusable="false">
        <g class="hero-circuit__wires"><use href="#hc-corner-wires"/></g>
        <g class="hero-circuit__pads"><use href="#hc-corner-pads"/></g>
        <g class="hero-circuit__rings"><use href="#hc-corner-rings"/></g>
        <g class="hero-circuit__charges">
          <use class="hero-circuit__charge hero-circuit__charge--c1" href="#hc-c7"/>
          <use class="hero-circuit__charge hero-circuit__charge--c2 hero-circuit__charge--back" href="#hc-c10"/>
          <use class="hero-circuit__charge hero-circuit__charge--c3" href="#hc-c12"/>
        </g>
        <g class="hero-circuit__nodes">
          <circle class="hero-circuit__node hero-circuit__node--i" cx="162.8" cy="38" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--j" cx="148.6" cy="74.2" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--k" cx="18.2" cy="210.4" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--l" cx="64.1" cy="193.7" r="3.6"/>
        </g>
      </svg>
      <svg class="hero-circuit__layer hero-circuit__layer--corner-tr" viewBox="0 0 200 215" preserveAspectRatio="xMinYMin meet" focusable="false">
        <g class="hero-circuit__wires"><use href="#hc-corner-wires"/></g>
        <g class="hero-circuit__pads"><use href="#hc-corner-pads"/></g>
        <g class="hero-circuit__rings"><use href="#hc-corner-rings"/></g>
        <g class="hero-circuit__charges">
          <use class="hero-circuit__charge hero-circuit__charge--c1" href="#hc-c7"/>
          <use class="hero-circuit__charge hero-circuit__charge--c2 hero-circuit__charge--back" href="#hc-c10"/>
          <use class="hero-circuit__charge hero-circuit__charge--c3" href="#hc-c12"/>
        </g>
        <g class="hero-circuit__nodes">
          <circle class="hero-circuit__node hero-circuit__node--m" cx="162.8" cy="38" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--n" cx="148.6" cy="74.2" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--o" cx="18.2" cy="210.4" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--p" cx="64.1" cy="193.7" r="3.6"/>
        </g>
      </svg>
      <svg class="hero-circuit__layer hero-circuit__layer--corner-bl" viewBox="0 0 200 215" preserveAspectRatio="xMinYMin meet" focusable="false">
        <g class="hero-circuit__wires"><use href="#hc-corner-wires"/></g>
        <g class="hero-circuit__pads"><use href="#hc-corner-pads"/></g>
        <g class="hero-circuit__rings"><use href="#hc-corner-rings"/></g>
        <g class="hero-circuit__charges">
          <use class="hero-circuit__charge hero-circuit__charge--c1" href="#hc-c7"/>
          <use class="hero-circuit__charge hero-circuit__charge--c2 hero-circuit__charge--back" href="#hc-c10"/>
          <use class="hero-circuit__charge hero-circuit__charge--c3" href="#hc-c12"/>
        </g>
        <g class="hero-circuit__nodes">
          <circle class="hero-circuit__node hero-circuit__node--q" cx="162.8" cy="38" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--r" cx="148.6" cy="74.2" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--s" cx="18.2" cy="210.4" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--t" cx="64.1" cy="193.7" r="3.6"/>
        </g>
      </svg>
      <svg class="hero-circuit__layer hero-circuit__layer--corner-br" viewBox="0 0 200 215" preserveAspectRatio="xMinYMin meet" focusable="false">
        <g class="hero-circuit__wires"><use href="#hc-corner-wires"/></g>
        <g class="hero-circuit__pads"><use href="#hc-corner-pads"/></g>
        <g class="hero-circuit__rings"><use href="#hc-corner-rings"/></g>
        <g class="hero-circuit__charges">
          <use class="hero-circuit__charge hero-circuit__charge--c1" href="#hc-c7"/>
          <use class="hero-circuit__charge hero-circuit__charge--c2 hero-circuit__charge--back" href="#hc-c10"/>
          <use class="hero-circuit__charge hero-circuit__charge--c3" href="#hc-c12"/>
        </g>
        <g class="hero-circuit__nodes">
          <circle class="hero-circuit__node hero-circuit__node--u" cx="162.8" cy="38" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--v" cx="148.6" cy="74.2" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--w" cx="18.2" cy="210.4" r="3.6"/>
          <circle class="hero-circuit__node hero-circuit__node--x" cx="64.1" cy="193.7" r="3.6"/>
        </g>
      </svg>
    </div>
<!--hero-circuit:end-->

<div class="container page-hero__inner">
      <h1 class="page-hero__title"><?= h($data['hero']['title']) ?></h1>
      <p class="page-hero__subtitle"><?= h($data['hero']['subtitle']) ?></p>
    </div>
  </section>

  <!-- ============================ Assets ============================= -->
<?php if (branding_band_shown($data, 'assets')): ?>
  <section class="section assets" aria-labelledby="assets-heading">
    <div class="container">
      <div data-reveal data-reveal-delay class="section__header">
        <span class="section__eyebrow"><?= h($data['assets']['eyebrow']) ?></span>
        <h2 class="section__title" id="assets-heading"><?= h($data['assets']['title']) ?></h2>
        <p class="section__lead">
          <?= h($data['assets']['lead']) ?>
        </p>
      </div>

      <div class="assets__grid">
<?php foreach (branding_rows_shown($data['assets']['items']) as $asset): ?>
        <article data-reveal data-reveal-delay class="asset">
          <div class="asset__preview asset__preview--<?= h($asset['plate']) ?>">
            <?= branding_picture($asset['image'], 'asset__image', (string)$asset['alt']) ?>
          </div>
          <div class="asset__body">
            <h3 class="asset__title"><?= h($asset['title']) ?></h3>
            <p class="asset__text"><?= h($asset['text']) ?></p>
            <?php /* The wrapper is what pins the buttons to a common line
                     across the row, and it exists because there can be more
                     than one of them: two anchors each claiming
                     margin-block-start:auto would split the free space between
                     themselves instead. One file or five, the group moves as
                     one. */ ?>
            <div class="asset__files">
<?php foreach (branding_rows_shown($asset['files']) as $file): ?>
              <p class="asset__meta"><?= h(branding_meta_line($file)) ?></p>
              <a class="btn btn--primary asset__download"
                 href="<?= h($file['file']['src']) ?>" download="<?= h($file['filename']) ?>">
                <svg class="icon icon--sm" aria-hidden="true" focusable="false"><use href="#arrow-down"></use></svg>
                <?= h(branding_download_label($file)) ?>
              </a>
<?php endforeach; ?>
            </div>
          </div>
        </article>
<?php endforeach; ?>
      </div>
    </div>
  </section>
<?php endif; ?>

  <!-- ========================== Disclaimer =========================== -->
<?php if (branding_band_shown($data, 'legal')): ?>
  <section class="section section--surface disclaimer" aria-labelledby="disclaimer-heading">
    <div class="container">
      <div data-reveal data-reveal-delay class="section__header">
        <h2 class="section__title" id="disclaimer-heading"><?= h($data['legal']['title']) ?></h2>
      </div>

      <div class="disclaimer__body">
<?php foreach (branding_rows_shown($data['legal']['items']) as $note): ?>
        <p data-reveal data-reveal-delay class="disclaimer__text"><?= $note['text'] ?></p>
<?php endforeach; ?>
      </div>
    </div>
  </section>
<?php endif; ?>

  <!-- ============================== CTA ============================== -->
<?php if (branding_band_shown($data, 'cta')): ?>
  <section class="cta-band cta-band--base">
    <div class="container cta-band__inner">
      <h2 data-reveal data-reveal-delay class="cta-band__title"><?= h($data['cta']['title']) ?></h2>
      <p data-reveal data-reveal-delay class="cta-band__text">
        <?= h($data['cta']['text']) ?>
      </p>
      <div data-reveal data-reveal-delay class="cta-band__actions">
<?php foreach (branding_rows_shown($data['cta']['items']) as $button): ?>
        <a class="btn btn--<?= h($button['style']) ?> btn--lg" href="<?= h($button['href']) ?>"><?= h($button['label']) ?></a>
<?php endforeach; ?>
      </div>
    </div>
  </section>
<?php endif; ?>

</main>

<?php body_footer(); ?>

<?php body_dock('/pages/branding-and-advertisement/'); ?>

<!-- Deferred so nothing blocks rendering. Order matters only in that main.js
     runs last: each module registers itself on window.Tech4Time, and main.js
     calls their init(). Pages that need no forms can omit forms.js. -->
<script src="/assets/js/theme-toggle.js" defer></script>
<script src="/assets/js/nav.js" defer></script>
<script src="/assets/js/animations.js?v=2" defer></script>
<script src="/assets/js/forms.js?v=2" defer></script>
<script src="/assets/js/dashboard.js" defer></script>
<script src="/assets/js/tech-sphere.js?v=2" defer></script>
<!-- Versioned for the same reason the stylesheets are, and with a sharper
     edge: MODULES in this file is a hardcoded allow list, so a stale copy
     silently skips every module added since — no error, no console line,
     just a feature that is not there. -->
<script src="/assets/js/circuit.js?v=7" defer></script>
<script src="/assets/js/main.js?v=3" defer></script>
</body>
</html>
