<?php
/**
 * Tech4TIME — what the site-wide footers currently say.
 *
 * GENERATED by tools/sync_site_contact.py. Do not edit by hand; run that.
 *
 * The footer's contact details are literal markup in all sixteen pages,
 * because the project forbids runtime partials. So the moment somebody edits
 * an address in the admin, the contact page is right and the footers are
 * behind — until the pages are rebuilt and deployed.
 *
 * This is the fingerprint of the details the footers were last rebuilt FOR.
 * api/publish.php returns it in every publish response, the backend records
 * what it was told, and the editor compares it against the details it now
 * holds. The frontend is the only side that knows what its own footers say,
 * so it is the side that answers.
 *
 * Not reachable over HTTP: .htaccess forbids /lib/.
 */

declare(strict_types=1);

const FOOTER_FINGERPRINT = '4d3f0075b40b7fb4e5b594735a8fe790bb36281e7b5be26da3db77c0e7de857f';
