<?php
/**
 * Tech4TIME — router for the local preview server.
 *
 * DEVELOPMENT ONLY. NEVER DEPLOYED.
 * It lives in tools/, which .htaccess blocks over HTTP, and it only ever runs
 * when it is passed to `php -S` by hand. Nothing on the web server loads it.
 *
 * WHY IT EXISTS
 * DirectoryIndex across both extensions. Apache is configured with
 * "index.html index.php"; this resolves a directory request the same way, so
 * /pages/careers/ finds its .php and every other page finds its .html.
 *
 * IT NO LONGER FAKES A SIGN-IN, AND THERE IS NOTHING HERE TO SIGN IN TO
 * It used to set REMOTE_USER, because /admin was protected by cPanel Directory
 * Privacy and admin/index.php would otherwise have refused to load. Both are
 * gone from this repository: the editor is tech4time-website-backend, with its
 * own accounts and its own serve.py. Nothing this router serves has a session.
 *
 * To work on the editor, run that repository's server; to watch content travel
 * between them, run both, as the docstring above describes.
 *
 * WHERE THE LOCAL SECRETS GO
 * lib/private.php puts them beside the document root, which here is the repo,
 * so they land in ../t4t-private — outside the tree, never committed, and the
 * same shape as /home/USER/t4t-private on the host. Set T4T_PRIVATE to put
 * them somewhere else; the test harnesses do, so a test run cannot disturb the
 * contact form's throttle counters, which are the only thing this half keeps
 * there — along with publish.key, and the master key that peppers the counters.
 *
 * Start it with tools/serve.py rather than by hand.
 */

declare(strict_types=1);

$root = dirname(__DIR__);
$path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) ?: '/';
$target = $root . rawurldecode($path);

/* What .htaccess refuses, refused here too.
   The local server does not read .htaccess, so every path the host answers 403
   for is reachable in development unless this says otherwise — and content/ is
   plain JSON, which the built-in server would hand over as a static file. The
   CI deploy probe asserts these are 403 on the live host; this is the same
   assertion for the machine the page is actually being written on. Section 8
   of .htaccess is the authoritative list; keep the two in step. */
$blocked = '#^/(lib|content|tools|references|t4t-private)/#';
$dotted  = '#(^|/)\.#';
if (preg_match($blocked, $path)
        || (preg_match($dotted, $path) && !str_starts_with($path, '/.well-known/'))) {
    http_response_code(403);
    header('Content-Type: text/plain; charset=utf-8');
    echo "403 Forbidden\n";
    return true;
}

/* The sitemap is generated by sitemap.php and served at /sitemap.xml, the
   address robots.txt names. .htaccess section 3 rewrites it on the host; this
   is the same rewrite for the local server. Without it the local sitemap is
   whatever static file happens to be lying about, which is the one thing this
   change removed. */
if ($path === '/sitemap.xml') {
    require $root . '/sitemap.php';
    return true;
}

/* Apache's DirectoryIndex, in its order. */
if (is_dir($target)) {
    foreach (['index.php', 'index.html'] as $name) {
        $candidate = rtrim($target, '/') . '/' . $name;
        if (is_file($candidate)) {
            $target = $candidate;
            break;
        }
    }
}

if (is_file($target) && str_ends_with($target, '.php')) {
    require $target;
    return true;
}

/* A service added in the editor has no directory in this repository, so its
   clean URL matches no file. .htaccess section 3 routes it to the shared
   renderer on the host; this does the same here, because neither of the two
   reads the other and a route that exists in only one of them is a route that
   works in only one place. The renderer answers 404 for a slug the document
   does not have, so an unknown address is still an unknown address. */
if (!is_file($target) && !is_dir($target)
        && preg_match('#^/pages/services/([a-z0-9-]+)/?$#', $path, $matches)) {
    $_GET['service'] = $matches[1];
    require $root . '/pages/services/detail.php';
    return true;
}

/* An address that resolves to nothing is a 404, and it has to be said here.
   The built-in server, asked for a directory it does not have, walks UP the
   tree looking for an index file and serves the first one it finds — so
   /pages/services/Anything/ answered 200 with the services index rather than
   404. That is documented behaviour of `php -S` and it is not what the host
   does: Apache 404s, and the visitor sees 404.html. A local server that
   answers a mistyped address with a real page is a local server that hides
   the fault being looked for. */
if (!is_file($target)) {
    http_response_code(404);
    require $root . '/404.html';
    return true;
}

/* Anything else: let the built-in server serve the file, or 404 it. */
return false;
